idf_component_register(SRCS "System/main.c" "System/task_registry.c" "System/Scheduler.c" "System/task.c" "input/LCD.c" "input/IMU_MPU.c" "input/IoT_Response.c" "System/ringbuff_com.c" "System/Com.c" "System/data_logger/data_logger.c" "System/data_logger/app_log.c" "System/data_logger/log_system.c" "System/communication/com_wifi.c" "System/communication/com_mqtt.c" "System/communication/com_ota.c" "System/communication/com_modbus_tcp.c" "System/communication/com_espnow.c" "System/communication/com_can.c" "System/communication/com_lora.c" "System/communication/com_uart.c"
                       PRIV_REQUIRES spi_flash esp_driver_i2c esp_driver_gpio esp_driver_twai driver esp_timer esp_ringbuf esp_wifi nvs_flash esp_netif esp_event esp_partition app_update esp_http_server mqtt
                       INCLUDE_DIRS "." "include" "input" "System/data_logger" "System/communication")