idf_component_register(SRCS "application_system/main.c" "application_system/application.c" "application_system/Scheduler.c" "application_system/task.c" "input/LCD.c" "input/IMU_MPU.c" "input/IoT_Response.c" "communication/ringbuff_com.c" "communication/COM.c" "data_logger/data_logger.c" "data_logger/app_log.c" "data_logger/log_system.c" "communication/com_wifi.c" "communication/com_mqtt.c" "communication/com_ota.c" "communication/com_modbus_tcp.c" "communication/com_espnow.c" "communication/com_can.c" "communication/com_lora.c" "communication/com_uart.c"
                       PRIV_REQUIRES spi_flash esp_driver_i2c esp_driver_gpio esp_driver_twai driver esp_timer esp_ringbuf esp_wifi nvs_flash esp_netif esp_event esp_partition app_update esp_http_server mqtt
                       INCLUDE_DIRS "." "include" "input" "application_system" "communication" "data_logger")